### PR TITLE
Feat: Add on-the-fly density-fitted fragment ERI transform

### PR DESCRIPTION
**Pull request by mscho527**
This PR adds an alternative way of generating the fragment ERIs. Instead of performing the initial mean-field calculation of the system using an `mol.incore_anyway = True` flag, one may perform a direct SCF calculation. Then, fragment ERIs are generated from density-fitted three-tensors that are calculated block-by-block on-the-fly. Under the assumption that the number of fragment orbitals are much smaller than that of the entire system atomic orbitals, this avoids the original memory bottleneck. (storing the ERI tensor or three-tensor in AO basis)

Output from an example run (343 atoms, def2-svp, BE2)
[svp_chmoptbe2.log](https://github.com/user-attachments/files/17101479/svp_chmoptbe2.log)

### CODE REVIEW

**Comment by oimeitei** [comment]
The attached output has large HF-in-HF error. How does this compare to the default? Converge the HF calculation to as tight as possible to see if the large error is from the HF calculation itself.

**Comment by mscho527** [comment]
> The attached output has large HF-in-HF error. How does this compare to the default? Converge the HF calculation to as tight as possible to see if the large error is from the HF calculation itself.

This is because the HF calculation was run with all the ERIs (direct SCF), whereas the fragment integrals were generated from density fitting. HF-in-HF error now includes the error introduced from DF (as noted in papers like [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10947126/)). If the HF calculation is run with DF, we don't have the relatively high error, but in cases we want to use on-the-fly DF, we would likely end up doing direct SCF.

**Comment by oimeitei** [comment]
> > The attached output has large HF-in-HF error. How does this compare to the default? Converge the HF calculation to as tight as possible to see if the large error is from the HF calculation itself.
> 
> This is because the HF calculation was run with all the ERIs (direct SCF), whereas the fragment integrals were generated from density fitting. HF-in-HF error now includes the error introduced from DF (as noted in papers like [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10947126/)). If the HF calculation is run with DF, we don't have the relatively high error, but in cases we want to use on-the-fly DF, we would likely end up doing direct SCF.

Can you make a note of this somewhere? maybe in `integral_direct_DF`

**Comment by mscho527** [comment]
Maybe this (octane, cc-pvTZ; used in the pytest routine in this PR) is a better example since none of the existing integral transformation routine in the code work for the huge former example (we run out of memory with incore).

[octane.log](https://github.com/user-attachments/files/17123058/octane.log)

**Comment by mscho527** [comment]
> > > The attached output has large HF-in-HF error. How does this compare to the default? Converge the HF calculation to as tight as possible to see if the large error is from the HF calculation itself.
> > 
> > 
> > This is because the HF calculation was run with all the ERIs (direct SCF), whereas the fragment integrals were generated from density fitting. HF-in-HF error now includes the error introduced from DF (as noted in papers like [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10947126/)). If the HF calculation is run with DF, we don't have the relatively high error, but in cases we want to use on-the-fly DF, we would likely end up doing direct SCF.
> 
> Can you make a note of this somewhere? maybe in `integral_direct_DF`

Yes! I've added this :)

**Pull request merged**
